GET http://localhost:3000/subscribers
###
GET http://localhost:3000/subscribers/5f90fbad457c2c005d235889
###
POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Billy Bob",
    "subscribedToChannel": "Influensir"
    
}

###
DELETE http://localhost:3000/subscribers/5f90fbad457c2c005d235889
###
PATCH http://localhost:3000/subscribers/5f90fbad457c2c005d235889
Content-Type: application/json

{
    "name": "New Name"
}